site_name: Accés a Dades
docs_dir: "md"
site_dir: "docs"
theme: material
nav:
  - Inici: index.md
  - Unitat 1. Fitxers:
    - Sistema de Fitxers: UD1_Files/1_File_System.md
    - Llegint i Escrivint: UD1_Files/2_Reading_and_writing_files.md
    - Treball amb Arxius XML: UD1_Files/3_XML_Files.md
    - Treball amb Arxius JSON: UD1_Files/4_JSON_Files.md
    - Altres formats de Fitxers: UD1_Files/5_Extra_Formats.md
  - Unitat 2. Connectors:
    - Desfase objecte-relacional: UD2_Connectors/1_Object_relational_impedance_mismatch.md
    - Connectors: UD2_Connectors/2_Connectors.md
    - Connectant-se a la base de dades: UD2_Connectors/3_Connecting.md
    - Resultats de les consultes: UD2_Connectors/4_Resultset.md
    - Metadades: UD2_Connectors/5_Metadata.md
    - Operacions CRUD: UD2_Connectors/6_CRUD.md
    - De les files als objectes: UD2_Connectors/7_Row_to_Object.md
  - Unitat 3. Hibernate:
    - Mapeig d'objectes: UD3_Hibernate/1_Mapping.md
    - Introduccio a Hibernate: UD3_Hibernate/2_Hibernate.md
    - Entitats: UD3_Hibernate/3_Entities_Beans.md
    - Relacions: UD3_Hibernate/4_Relationships.md
    - Consultes: UD3_Hibernate/5_HQL.md
  - Unitat 4. Bases de Dades OO:
    - Introduccio a les bases de dades OO: UD4_BDOO/1_Introduction.md
    - Bases de dades Objecte-Relacionals: UD4_BDOO/2_ORDB.md
    - Bases de dades Orientades a Objectes: UD4_BDOO/3_OODB.md
  - Unitat 5. Spring: 
    - Serveis d'Acces a Dades: UD5_Spring/1_Data_Access_Services.md
    - Introducció a Spring: UD5_Spring/2_Spring_SpringBoot.md
    - Creació de APIs REST: UD5_Spring/3_API_Rest.md
    - Seguretat: UD5_Spring/4_Spring_Security.md
    - Spring Haetoas: UD5_Spring/5_Spring_Hateoas.md
    - Test. Postman i Swagger: UD5_Spring/6_Postman_Swagger.md 
  - Unitat 6. MongoDB: 
    - Bases de Dades NoSQL: UD6_MongoDB/1_NoSQL.md
    - Introducció a MongoDB: UD6_MongoDB/2_MongoDB.md
    - Operacions amb Shell: UD6_MongoDB/3_ShellOperations.md
    - Consultes CRUD: UD6_MongoDB/4_Queries.md
    - Mongo i Java: UD6_MongoDB/5_Mongo_Java.md
    - Spring Data MongoDB: UD6_MongoDB/6_Spring_MongoDB.md
#  - Pràctiques:
#    - Pràctica 1: Practiques/APAC1.md
#    - Pràctica 2: Practiques/APAC2.md
#    - Pràctica 3: Practiques/APAC3.md
#    - Pràctica 4: Practiques/APAC4.md
#    - Pràctica 5: Practiques/APAC5.md

  - Sobre mi: about.md
  - Llicència: license.md


plugins:
  - search
#  - with-pdf:   #https://github.com/orzih/mkdocs-with-pdf
#      author: Joan Gerard Camarena Estruch


#  - i18n:
#      docs_structure: suffix
#      languages:
#        - locale: ca
#          name: Valencia
#          default: true
#          build: true
##        - locale: en
#          name: English
#          build: true
#          nav_translations:
#            Accés a Dades: Data Access
#            Inici: Index
#            Sobre mi: About me
#            Llicència: License
#            Unitat 1. Fitxers: Unit 1. Files
#            Sistema de Fitxers: File System
#            Llegint i Escrivint: Reading and Writing Files
#            Treball amb Arxius XML: Working with XML Files
#            Treball amb Arxius JSON: Working with JSON Files
#            Altres formats de Fitxers: Other File Formats
#            Unitat 2. Connectors: Unit 2. Connectors
#            Desfase objecte-relacional: Object-relational impedance mismatch
#            Connectors: Connectors
#            Connectant-se a la base de dades: Connecting to the database
#            Resultats de les consultes: Query results
#            Metadades: Metadata
#            Operacions CRUD: CRUD Operations
#            De les files als objectes: From rows to objects
#            Unitat 3. Hibernate: Unit 3. Hibernate
#            Mapeig d'objectes: Object mapping
#            Introduccio a Hibernate: Introduction to Hibernate
#            Entitats:  Entities
#            Relacions: Relationships
#            Consultes: Queries
#            Unitat 4. Bases de Dades OO: Unit 4. OO Databases
#            Introduccio a les bases de dades OO: Introduction to OO Databases
#            Bases de dades Objecte-Relacionals: Objet-Relational Databases
#            Bases de dades Orientades a Objectes: Object-Oriented Databases
#            Unitat 5. Spring: Unit 5. Spring 
#            Serveis d'Acces a Dades: Data Access Services
#            Introducció a Spring: Introduction to Spring
#            Creació de APIs REST: Creating REST APIs
#            Seguretat: Security
#            Spring Haetoas: Spring Hateoas 
#            Test. Postman i Swagger: Test. Postman and Swagger
#            Unitat 6. MongoDB: Unit 6. MongoDB 
#            Bases de Dades NoSQL: NoSQL Databases
#            Introducció a MongoDB: Introduction to MongoDB
#            Operacions amb Shell: Shell Operations
#            Consultes CRUD: CRUD Queries
#            Mongo i Java: Mongo and Java
#            Spring Data MongoDB: Spring MongoDB
#            Pràctiques: Practices
#            Pràctica 1: Practice 1
##            Pràctica 2: Practice 2
#            Pràctica 3: Practice 3
#            Pràctica 4: Practice 4
#            Pràctica 5: Practice 5

theme: 
  name: material
  logo: ./assets/jaume.png
  favicon: ./assets/jaume.png
  language: ca 
  palette:
#    # Palette toggle for light mode
    - scheme: default
      primary: deep purple
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
        
    # Palette toggle for dark mode
    - scheme: slate
      primary: brown
      toggle:
        icon: material/brightness-4
        name: Switch to light mode 
        primary: grey   
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate

markdown_extensions: 
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  alternate:
    # Switch to English
    - name: English
      link: "en"
      lang: en

    # Switch to Valencia
    - name: Valencià
      link: ""
      lang: ca